/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.hska.iwi.avg.schufasystem.service.SchufaService;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Business implements org.apache.thrift.TEnum {
  telco(1),
  energy(2),
  retail(3),
  finance(4);

  private final int value;

  private Business(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Business findByValue(int value) { 
    switch (value) {
      case 1:
        return telco;
      case 2:
        return energy;
      case 3:
        return retail;
      case 4:
        return finance;
      default:
        return null;
    }
  }
}
